# Generated by Django 4.2.6 on 2023-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_Email', models.EmailField(max_length=100)),
                ('admin_password', models.CharField(max_length=10)),
                ('admin_repeat_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('repeat_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
