# Generated by Django 4.2.6 on 2023-10-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_admin_login_student_register_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_student',
            old_name='Email',
            new_name='email',
        ),
    ]
