# Generated by Django 4.2.6 on 2023-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_login_admin_user_login_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_admin',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login_admin',
            old_name='admin_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='login_student',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='register_admin',
            old_name='admin_Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register_admin',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register_admin',
            old_name='admin_repeat_password',
            new_name='repeat_password',
        ),
        migrations.AddField(
            model_name='register_student',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_admin',
            name='user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register_student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
