# Generated by Django 4.2.6 on 2024-01-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_admin_password_login_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_admin',
            old_name='user',
            new_name='username',
        ),
    ]
