# Generated by Django 4.2.6 on 2024-01-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_register_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='login_student',
            name='user',
        ),
    ]
