# Generated by Django 4.2.6 on 2024-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_login_admin_user_login_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_admin',
            name='username',
        ),
        migrations.AlterField(
            model_name='register_admin',
            name='user',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
