# Generated by Django 4.2.6 on 2024-01-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_addstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
