# Generated by Django 4.2.6 on 2024-01-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_addcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcourse',
            old_name='classname',
            new_name='username',
        ),
    ]
