# Generated by Django 4.2.6 on 2024-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_classname_addcourse_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='room_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
