# Generated by Django 4.2.6 on 2024-01-02 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0007_alter_addcourse_room_number_alter_addcourse_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
