# Generated by Django 4.2.6 on 2024-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_student_rename_serviceadmin_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='courses',
            field=models.ManyToManyField(to='service.addcourse'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment',
            field=models.FileField(default=1, upload_to='Assignment/'),
            preserve_default=False,
        ),
    ]
