# Generated by Django 4.2.6 on 2024-01-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_addstudent_courses_student_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='courses',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.addcourse'),
        ),
    ]
