# Generated by Django 4.2.6 on 2024-01-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_assignmentupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentupload',
            old_name='username',
            new_name='assignment_name',
        ),
    ]
