# Generated by Django 4.2.6 on 2024-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_rename_username_assignmentupload_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentupload',
            name='assignment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
