# Generated by Django 4.2.6 on 2024-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_assignmentupload_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentupload',
            name='assignment_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
