# Generated by Django 4.2.6 on 2024-03-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_assignmentupload_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpannel',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
