# Generated by Django 4.2.6 on 2024-03-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_studentpannel_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
