# Generated by Django 4.2.6 on 2024-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentupload',
            name='folder_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentupload',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
