# Generated by Django 4.2.6 on 2024-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_assignmentupload_assignment_addassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addassignment',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='addassignment',
            name='name',
        ),
        migrations.AlterField(
            model_name='addassignment',
            name='assignmnet_file',
            field=models.CharField(max_length=1000),
        ),
    ]
