# Generated by Django 4.2.6 on 2024-03-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_remove_addassignment_folder_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addassignment',
            old_name='assignmnet_file',
            new_name='assignment_file',
        ),
    ]
