# Generated by Django 4.2.6 on 2024-03-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_rename_assignmnet_file_addassignment_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='addassignment',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.addcourse'),
            preserve_default=False,
        ),
    ]
