# Generated by Django 4.2.6 on 2024-03-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_addassignment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addassignment',
            name='username',
        ),
    ]
