# Generated by Django 4.2.6 on 2024-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_remove_addassignment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addassignment',
            name='classname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
