# Generated by Django 4.2.6 on 2024-03-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_addassignment_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addassignment',
            old_name='classname',
            new_name='username',
        ),
    ]
