# Generated by Django 4.2.6 on 2024-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_rename_classname_addassignment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addassignment',
            name='answer',
            field=models.FileField(default=1, upload_to='Answer/'),
            preserve_default=False,
        ),
    ]
